### ISSUE TITLE
TOPK排行榜设计里是不是有些许bug

### ISSUE THREAD

**Issue by snaper1** [tzheng/interviewprep#1]
假如堆中一个数据过期前，存在一些新数据入堆失败（比堆顶小，没竞争过），该数据过期后，刚刚新数据就丢失了

**Comment by tzheng** [comment]
hi, 堆只是用来存top k 用的，是为了方便query的时候能迅速读出top k，堆并不是用来做所有的数据的存储，否则效率很低。
在设计中，我们有提到

> 当写频繁的时候，如果直接每次更新堆，频繁改动堆效率也十分低下。所以我们还需要通过其他数据结构作为辅助。这里我们可以选用队列(Queue)和哈希表(HashMap)。

所以其实我们在内存中还维护了一个 Map<String, Long> 存放每个话题出现的次数，和一个Queue<Map<String, Long>>，队列中的每一个元素对应30秒，假设我们只要top 2, 并且开始的时候有 
```
Map: 
A -> 0, B -> 0, C:-> 0

Heap:
A -> 0, B -> 0

Queue
30s ->  {A: 30, B:20, C:10}
60s ->  {A: 10, B:10, C:50}
```
在第30秒的时候，我们会根据队列里面的 `30s ->  {A: 30, B:20, C:10}`， 去更新Map, 在更新map的时候，我们同时和堆比较一下，这里是A和B最多，所以变成
```
Map: 
A -> 30, B -> 20, C:-> 10

Heap:
A -> 30, B -> 20

Queue
30s ->  {A: 30, B:20, C:10}
60s ->  {A: 10, B:10, C:50}
```

在第60秒的时候，我们会根据队列里面的`60s ->  {A: 10, B:10, C:50}`， 去更新Map, 同时吧前30秒的减去，这时候有 
```
Map: 
A -> 10, B -> 10, C:-> 50

Heap
C-> 50, A-> 10
```

例子举得简单了一点， 大致意思就是在更新哈希表里面每个元素的时候，我们都把该元素和堆里面的元素对比，到 C的时候，发现C的次数已经多于B了，我们就更新堆了，这样并不会丢失任何东西。

**Comment by tzheng** [comment]
> 假如堆中一个数据过期前，存在一些新数据入堆失败（比堆顶小，没竞争过），该数据过期后，刚刚新数据就丢失了

hi, 堆只是用来存top k 用的，是为了方便query的时候能迅速读出top k，堆并不是用来做所有的数据的存储，否则效率很低。
在设计中，我们有提到

> 当写频繁的时候，如果直接每次更新堆，频繁改动堆效率也十分低下。所以我们还需要通过其他数据结构作为辅助。这里我们可以选用队列(Queue)和哈希表(HashMap)。

所以其实我们在内存中还维护了一个 Map<String, Long> 存放每个话题出现的次数，和一个Queue<Map<String, Long>>，队列中的每一个元素对应30秒，假设我们只要top 2, 并且开始的时候有

Map: 
A -> 0, B -> 0, C:-> 0

Heap:
A -> 0, B -> 0

Queue
30s ->  {A: 30, B:20, C:10}
60s ->  {A: 10, B:10, C:50}
在第30秒的时候，我们会根据队列里面的 30s -> {A: 30, B:20, C:10}， 去更新Map, 在更新map的时候，我们同时和堆比较一下，这里是A和B最多，所以变成

Map: 
A -> 30, B -> 20, C:-> 10

Heap:
A -> 30, B -> 20

Queue
30s ->  {A: 30, B:20, C:10}
60s ->  {A: 10, B:10, C:50}
在第60秒的时候，我们会根据队列里面的60s -> {A: 10, B:10, C:50}， 去更新Map, 同时吧前30秒的减去，这时候有

Map: 
A -> 10, B -> 10, C:-> 50

Heap
C-> 50, A-> 10
例子举得简单了一点， 大致意思就是在更新哈希表里面每个元素的时候，我们都把该元素和堆里面的元素对比，到 C的时候，发现C的次数已经多于B了，我们就更新堆了，这样并不会丢失任何东西。

**Comment by snaper1** [comment]
thx，理解错了，统计过程是按时间桶来统计。
